apiVersion: apps/v1
kind: Deployment

metadata:  #Deployment identity.
  name: opspulse-deployment #Deployment name
  namespace: opspulse

spec:
  replicas: 2

  selector:
    matchLabels:
      app: opspulse

  template:
    metadata:
      labels:
        app: opspulse

    spec:
      containers:
        - name: opspulse
          image: ghcr.io/techsheetalsrivastava/opspulse:latest
          ports:
            - containerPort: 3000
