apiVersion: v1
kind: Service

metadata:
  name: opspulse-service
  namespace: opspulse

spec:
  selector:
    app: opspulse

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

  type: ClusterIP